### ISSUE TITLE
能不能别限制caj文件，kdh文件也能转换

### ISSUE THREAD

**Issue by ChenXin2021** [sainnhe/caj2pdf-qt#17]

**Comment by sainnhe** [comment]
这个其实早就在 Todo 里面了，只不过我手里没有 kdh 文件，网上也搜不到，所以没办法进行测试。你有 kdh 文件吗，能否发一些给我让我测一下。

**Comment by luanxiaoyun** [comment]
我这有KHD文件，贴在附件链接了，等一个KHD转pdf
[9.4T磁共振成像系统高通鸟笼射频线圈的研制.zip](https://github.com/sainnhe/caj2pdf-qt/files/14581779/9.4T.zip)

**Comment by ChenXin2021** [comment]
能转的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月13日(周三) 中午11:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sainnhe/caj2pdf-qt] 能不能别限制caj文件，kdh文件也能转换 (Issue #17)




 
我这有KHD文件，贴在附件链接了，等一个KHD转pdf
 9.4T磁共振成像系统高通鸟笼射频线圈的研制.zip

**Comment by luanxiaoyun** [comment]
转不了呀，选都不能选KHD文件

**Comment by ChenXin2021** [comment]
将khd文件后缀改为caj，就可以了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月13日(周三) 下午2:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sainnhe/caj2pdf-qt] 能不能别限制caj文件，kdh文件也能转换 (Issue #17)




 
转不了呀，选都不能选KHD文件

**Comment by sainnhe** [comment]
https://github.com/sainnhe/caj2pdf-qt/commit/1fc1ffcd432ca587b0b286423edfa721fdc376fc

已经实现了，将在下个版本中支持

**Comment by sainnhe** [comment]
v0.1.6 已发布 https://github.com/sainnhe/caj2pdf-qt/releases/tag/v0.1.6
