### ISSUE TITLE
文件拖入及批量处理需求

### ISSUE THREAD

**Issue by ScienceZone** [sainnhe/caj2pdf-qt#2]
首先感谢你提供的工具为大家带来了便利，其次是想提一下功能改进建议：1. 希望可以支持将文件文件直接拖入软件界面处理，因为有时文档路径真不太好找，光是选择路径就用时好久，有点费时。2. 希望可以支持批量处理文件，因为有时查找某个问题，下载了不少文献，挨个处理有点费事费力，效率太低。谢谢！

**Comment by sainnhe** [comment]
批量处理已经实现了，你直接选择多个文件就行。

文件拖拽我找时间看一下。

**Comment by sainnhe** [comment]
哦，你说的选择多文件是不是指多点几次选择文件按钮？这个操作逻辑确实还没考虑到，一会可以加上。

**Comment by ScienceZone** [comment]
主要还是选择路径麻烦，支持一下拖拽就可以了。另外转换进度显示不准确，普通理解是显示100%时应该能看到转换完成时文件，但是我转换了3个文件，文件夹下过了一会才出现2个，第三个等一会还没出现，重新对其转换才成功。谢谢！



---原始邮件---
发件人: "Sainnhe ***@***.***&gt;
发送时间: 2022年4月13日(周三) 下午3:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sainnhe/caj2pdf-qt] 文件拖入及批量处理需求 (Issue #2)




 
哦，你说的选择多文件是不是指多点几次选择文件按钮？这个操作逻辑确实还没考虑到，一会可以加上。

**Comment by sainnhe** [comment]
已经实现了，等我再实现几个功能再发布新版本。

**Comment by sainnhe** [comment]
新版发布了。
