### ISSUE TITLE
Mac下打不开.Apple芯片(ARM架构)

### ISSUE THREAD

**Issue by LanYunDev** [sainnhe/caj2pdf-qt#3]
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/95263282/165870256-4a5a3d35-4e18-41ee-9460-086f4b91e07d.png">
<img width="586" alt="image" src="https://user-images.githubusercontent.com/95263282/165870291-1f6c470a-78da-4ae1-8812-a44a419f9c66.png">

**Comment by LanYunDev** [comment]
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               caj2pdf [24381]
Path:                  /Users/USER/Downloads/caj2pdf.app/Contents/MacOS/caj2pdf
Identifier:            dev.sainnhe.caj2pdf-qt
Version:               0.1 (0.1.4)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-04-29 08:57:58.6305 +0800
OS Version:            macOS 12.3.1 (21E258)
Report Version:        12
Anonymous UUID:        45766FCD-D3FD-B3CF-BD92-66324EB4DF58

Sleep/Wake UUID:       D13ABF36-83D3-4E27-B1BC-457986E7454D

Time Awake Since Boot: 380000 seconds
Time Since Wake:       2583 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @rpath/QtWidgets.framework/Versions/A/QtWidgets
Referenced from: /Users/USER/Downloads/caj2pdf.app/Contents/MacOS/caj2pdf
Reason: tried: '/opt/local/libexec/qt6/lib/QtWidgets.framework/Versions/A/QtWidgets' (no such file), '/opt/local/libexec/qt6/lib/QtWidgets.framework/Versions/A/QtWidgets' (no such file), '/Library/Frameworks/QtWidgets.framework/Versions/A/QtWidgets' (no such file), '/System/Library/Frameworks/QtWidgets.framework/Versions/A/QtWidgets' (no such file)
(terminated at launch; ignore backtrace)

Application Specific Information:
Library not loaded: @rpath/QtWidgets.framework/Versions/A/QtWidgets
Referenced from: /Users/lanyun/Downloads/caj2pdf.app/Contents/MacOS/caj2pdf
Reason: tried: '/opt/local/libexec/qt6/lib/QtWidgets.framework/Versions/A/QtWidgets' (no such file), '/opt/local/libexec/qt6/lib/QtWidgets.framework/Versions/A/QtWidgets' (no such file), '/Library/Frameworks/QtWidgets.framework/Versions/A/QtWidgets' (no such file), '/System/Library/Frameworks/QtWidgets.framework/Versions/A/QtWidgets' (no such file)


Thread 0 Crashed:
0   dyld                          	       0x104def82c __abort_with_payload + 8
1   dyld                          	       0x104df69ec abort_with_payload_wrapper_internal + 104
2   dyld                          	       0x104df6a20 abort_with_payload + 16
3   dyld                          	       0x104dae91c dyld4::halt(char const*) + 328
4   dyld                          	       0x104da9fb4 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3644
5   dyld                          	       0x104da9068 start + 484


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000016b27aa40   x3: 0x000000000000007f
    x4: 0x000000016b27a640   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000560
    x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x0000000000000001  x11: 0x000000000000000a
   x12: 0x0000000000000000  x13: 0x0000000000000032  x14: 0x000000026ebc94c5  x15: 0x0000000000000000
   x16: 0x0000000000000209  x17: 0x0000000104da714c  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016b27a640  x21: 0x000000000000007f  x22: 0x000000016b27aa40  x23: 0x0000000000000001
   x24: 0x0000000000000006  x25: 0x000000016b27b388  x26: 0x0000000000000000  x27: 0x000000001f070004
   x28: 0x0000000000000000   fp: 0x000000016b27a610   lr: 0x0000000104df69ec
    sp: 0x000000016b27a5d0   pc: 0x0000000104def82c cpsr: 0x00001000
   far: 0x0000000104cc4000  esr: 0x56000080  Address size fault

Binary Images:
       0x104da4000 -        0x104e03fff dyld (*) <fbb89662-e6f2-3434-b542-f75185ac5e74> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=816K resident=0K(0%) swapped_out_or_unallocated=816K(100%)
Writable regions: Total=9216K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9216K(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8176K        1 
VM_ALLOCATE                         16K        1 
__DATA                              32K        2 
__DATA_CONST                       112K        2 
__LINKEDIT                         336K        2 
__TEXT                             480K        2 
dyld private memory               1024K        1 
===========                     =======  ======= 
TOTAL                             66.0M       12 



-----------
Full Report
-----------

{"app_name":"caj2pdf","timestamp":"2022-04-29 08:57:58.00 +0800","app_version":"0.1","slice_uuid":"6747a896-2be0-39f3-aad3-1a1674259de5","build_version":"0.1.4","platform":1,"bundleID":"dev.sainnhe.caj2pdf-qt","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.3.1 (21E258)","incident_id":"87A30D14-5B1B-47CC-A470-708B78298FC9","name":"caj2pdf"}
{
  "uptime" : 380000,
  "procLaunch" : "2022-04-29 08:57:58.6048 +0800",
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,2",
  "procStartAbsTime" : 9232123721555,
  "coalitionID" : 44692,
  "osVersion" : {
    "train" : "macOS 12.3.1",
    "build" : "21E258",
    "releaseType" : "User"
  },
  "captureTime" : "2022-04-29 08:57:58.6305 +0800",
  "incident" : "87A30D14-5B1B-47CC-A470-708B78298FC9",
  "bug_type" : "309",
  "pid" : 24381,
  "procExitAbsTime" : 9232124057887,
  "translated" : false,
  "cpuType" : "ARM-64",
  "procName" : "caj2pdf",
  "procPath" : "\/Users\/USER\/Downloads\/caj2pdf.app\/Contents\/MacOS\/caj2pdf",
  "bundleInfo" : {"CFBundleShortVersionString":"0.1","CFBundleVersion":"0.1.4","CFBundleIdentifier":"dev.sainnhe.caj2pdf-qt"},
  "storeInfo" : {"deviceIdentifierForVendor":"09107AE7-9D34-5BA0-931D-A0C656BE2235","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "dev.sainnhe.caj2pdf-qt",
  "crashReporterKey" : "45766FCD-D3FD-B3CF-BD92-66324EB4DF58",
  "wakeTime" : 2583,
  "sleepWakeUUID" : "D13ABF36-83D3-4E27-B1BC-457986E7454D",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: @rpath\/QtWidgets.framework\/Versions\/A\/QtWidgets","Referenced from: \/Users\/USER\/Downloads\/caj2pdf.app\/Contents\/MacOS\/caj2pdf","Reason: tried: '\/opt\/local\/libexec\/qt6\/lib\/QtWidgets.framework\/Versions\/A\/QtWidgets' (no such file), '\/opt\/local\/libexec\/qt6\/lib\/QtWidgets.framework\/Versions\/A\/QtWidgets' (no such file), '\/Library\/Frameworks\/QtWidgets.framework\/Versions\/A\/QtWidgets' (no such file), '\/System\/Library\/Frameworks\/QtWidgets.framework\/Versions\/A\/QtWidgets' (no such file)"]},
  "asi" : {"dyld":["Library not loaded: @rpath\/QtWidgets.framework\/Versions\/A\/QtWidgets","Referenced from: \/Users\/lanyun\/Downloads\/caj2pdf.app\/Contents\/MacOS\/caj2pdf","Reason: tried: '\/opt\/local\/libexec\/qt6\/lib\/QtWidgets.framework\/Versions\/A\/QtWidgets' (no such file), '\/opt\/local\/libexec\/qt6\/lib\/QtWidgets.framework\/Versions\/A\/QtWidgets' (no such file), '\/Library\/Frameworks\/QtWidgets.framework\/Versions\/A\/QtWidgets' (no such file), '\/System\/Library\/Frameworks\/QtWidgets.framework\/Versions\/A\/QtWidgets' (no such file)"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":23031278,"threadState":{"x":[{"value":6},{"value":1},{"value":6092728896},{"value":127},{"value":6092727872},{"value":0},{"value":0},{"value":1376},{"value":32},{"value":9},{"value":1},{"value":10},{"value":0},{"value":50},{"value":10447787205},{"value":0},{"value":521},{"value":4376392012,"symbolLocation":392,"symbol":"__simple_bprintf"},{"value":0},{"value":0},{"value":6092727872},{"value":127},{"value":6092728896},{"value":1},{"value":6},{"value":6092731272},{"value":0},{"value":520552452},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4376717804},"cpsr":{"value":4096},"fp":{"value":6092727824},"sp":{"value":6092727760},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":4376688684,"matchesCrashFrame":1},"far":{"value":4375461888}},"frames":[{"imageOffset":309292,"symbol":"__abort_with_payload","symbolLocation":8,"imageIndex":0},{"imageOffset":338412,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":104,"imageIndex":0},{"imageOffset":338464,"symbol":"abort_with_payload","symbolLocation":16,"imageIndex":0},{"imageOffset":43292,"symbol":"dyld4::halt(char const*)","symbolLocation":328,"imageIndex":0},{"imageOffset":24500,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3644,"imageIndex":0},{"imageOffset":20584,"symbol":"start","symbolLocation":484,"imageIndex":0}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4376379392,
    "size" : 393216,
    "uuid" : "fbb89662-e6f2-3434-b542-f75185ac5e74",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 7370014720,
  "size" : 3136438272,
  "uuid" : "1df3dfc1-141a-35d0-a4e5-f1e113894c6e"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=816K resident=0K(0%) swapped_out_or_unallocated=816K(100%)\nWritable regions: Total=9216K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9216K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8176K        1 \nVM_ALLOCATE                         16K        1 \n__DATA                              32K        2 \n__DATA_CONST                       112K        2 \n__LINKEDIT                         336K        2 \n__TEXT                             480K        2 \ndyld private memory               1024K        1 \n===========                     =======  ======= \nTOTAL                             66.0M       12 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "6103050cbfe6dc472e1c982a"
      },
      "deploymentId" : 240000066
    },
    {
      "rolloutId" : "6112e14f37f5d11121dcd519",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "6267122541fbd3022330c3ea"
      },
      "deploymentId" : 240000110
    }
  ],
  "experiments" : [

  ]
}
}

**Comment by sainnhe** [comment]
忘了 deploy，试试看最新的 release 呢

**Comment by LanYunDev** [comment]
最新的release暂未发布

**Comment by LanYunDev** [comment]
<img width="260" alt="image" src="https://user-images.githubusercontent.com/95263282/165951582-1dcfea84-9aea-4259-9e08-5343b93154e8.png">

**Comment by LanYunDev** [comment]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/95263282/165952750-9fbdb6fe-4a50-4e52-9e68-daf0b8550f6b.png">
通过绕过签名解决了.
