### ISSUE TITLE
Entry point not found (api-ms-win-core-synch-l1-2-0.dll)

### ISSUE THREAD

**Issue by m-xh** [sainnhe/caj2pdf-qt#4]
你好

打开exe时显示 Entry point not found (api-ms-win-core-synch-l1-2-0.dll)

dll 文件夹下有相应文件

系统是德语win 7pro

谢谢

**Comment by sainnhe** [comment]
刚才查了一下，好像需要 VC 运行时 https://answers.microsoft.com/en-us/windows/forum/all/api-ms-win-core-synch-l1-2-0-dll-problem/b5df6724-2274-46bd-aabf-e4201b55ce8d

你可以试试安装这个吗？
