### ISSUE TITLE
macos版本可以降低系统版本要求嘛

### ISSUE THREAD

**Issue by xiongsp** [sainnhe/caj2pdf-qt#6]
我正在使用10.15版本，不知道这个应用可不可以支持到比11.6更低的版本

**Comment by sainnhe** [comment]
我手里没有x86的机子，你可以自己编译 https://github.com/sainnhe/caj2pdf-qt/blob/master/BUILD.md#macos

如果你用的是 macports 也可以从我的个人仓库安装 https://repo.sainnhe.dev/macports/

**Comment by xiongsp** [comment]
可以请教一下jbig2dec的安装方法嘛 我自行编译的时候这个环境不太会安装

**Comment by sainnhe** [comment]
homebrew 和 macports 都有这个包
